import persistence as ps

translations = {
    "settings_title": "Ajustes",
    "advanced_settings_title": "Ajustes avanzados",
    "back": "Atrás",
    "volume": "Volumen",
    "ter_sound_on": "Sonidos terminal: Sí",
    "ter_sound_off": "Sonidos terminal: No",
    "save_played": "Guardar partidas: ",
    "on": "Sí",
    "off": "No",
    "sound": "Sonido del juego: ",
    "alt_control": "Modo teclado: ",
    "show_timer": "Mostrar tiempo: ",
    "milliseconds": "con milisegundos: ",
    "fullscreen": "Pantalla completa: ",
    "live_clock": "Hora: ",
    "ultra_timer": "Tiempo Ultra: ",
    "ultra_ms": "Milisegundos Ultra: ",
    "ultra_clock": "Hora terminal: ",
    "game_volume": "Volumen del juego",
    "terminal_volume": "Volumen terminal",
    "language": "Idioma",
    "u_ter_in_ord": "Orden de entrada del terminal Ultra",
    "keybindings": "Atajos",
    "key_press": "Pulsa una tecla",
    "about_1": "Sobre Mati",
    "about_2": "Mati es un algoritmo. Y uno realemente genial.",
    "about_3": "Genera el tablero interno y elige casillas al azar.",
    "about_4": "Las casillas elegidas se suman y se anotan los resultados.",
    "about_5": "Creado por:",
    "size": "Tamaño",
    "mode": "Modo",
    "games": "Victorias",
    "best": "Mejor tiempo",
    "average": "Tiempo medio",
    "achievements": "Logors",
    "unlocked": " desbloqueado",
    "unlocked_overall": " desbloqueados en total",
    "nothing achieved": "Aún no has completado nada.",
    "page": "Página",
    "delete_match": "¿Borrar partida?",
    "under_1": "¿Seguro que quieres borrar esta partida",
    "under_2": "permanentement de tu historial?",
    "delete": "Borrar",
    "cancel": "Cancelar",
    "menu": "Menú",
    "no_history_entries": "No hay partidas guardadas, al menos por ahora.",
    "all": "Todas",
    "no_matches": "Ninguna partida coincide con tus filtros activos.",
    "mati": "Mati",
    "intro_text": "Pensamiento matemático y táctico",
    "settings": "Ajustes",
    "history": "Historial",
    "quit": "Salir",
    "gameplay": "Mecánica de juego",
    "timer": "Tiempo de juego",
    "ultra_mode": "Mode Ultra",
    "display": "Pantalla",
    "stats": "Estadísticas",
    "about": "Sobre",
    "fullscreen_info": "Pulsa F11 para cambiar o ESC para salir del modo de pantalla completa.",
    "ultra": "ULTRA",
    "ultra_1": "Ultra",
    "normal": "Normal",
    "time": "Tiempo: ",
    "hints": "Asistencia: ",
    "action_start": "Acción: Inicio",
    "action": "Acción: ",
    "row": " (Fila: ",
    "column": " / Columna: ",
    "end": "Fin de la partida",
    "export": "Exportae como MP4",
    "show_end": "Mostrar resultado",
    "start": "Inicio",
    "action_found": "No se encontraron acciones",
    "continue": "Continuar",
    "new": "Nuevo",
    "undo": "Deshacer",
    "hint": "Pista ",
    "won": "Has ganado",
    "paused": "En pausa",
    "pressing": "Pulsa ",
    "contin": " o <<Continuar>> para seguir jugando",
    "unfinished": "Partidas pausadas encontradas",
    "ask_return": "¿Quieres continuar o iniciar una partida nueva?",
    "new_game": "Nueva partida",
    "resume": "Continuar",
    "break": "Pause",
    "histo": "Historial",
    "Easy": "Fácil",
    "Advanced": "Avanzado",
    "Hard": "Difícil",
    "Expert": "Experto",
    "Select": "Seleccionado",
    "Mark": "Marcado",
    "Hint": "Pista",
    "Undone": "Deshecho",
    "hannah_com": "Hannah - Mensaje completado",
    "hannah_fou": "Hannah - Mensaje encontrado",
    "Column, Row, Action": "Columna, Fila, Acción",
    "Row, Column, Action": "Fila, Columna, Acción",
    "Action, Row, Column": "Acción, Fila, Columna",
    "Action, Column, Row": "Acción, Columna, Fila",
    "Back to Menu": "Volver al menú",
    "New Round": "Nueva ronda",
    "Toggle Fullscreen": "Pantalla completa",
    "Use Hint": "Pista",
    "Undo": "Deshacer",
    "Pause": "Pausa",
    "Right-Click Cell": "Marcar casilla",
    "Standard": "Estándar",
    "High": "Alto",
    "Ultra": "Ultra",
    "Highest": "Máximo",
    "milestones_reached": "Hitos logrados",
    "left": "Restante",
    "hover_to_browse": "Pasa el cursor para explorar",
    "scroll_to_browse": "Desplázate para explorar",
    "games_played": "Partidas jugadas",
    "total_playtime": "Tiempo total de juego",
}

with open("rsc/languages/espanol.smati", "w") as f:
    f.write(ps._encode(translations))