import persistence as ps

translations = {
    "settings_title": "Paramètres",
    "advanced_settings_title": "Paramètres avancés",
    "back": "Retour",
    "volume": "Volume",
    "ter_sound_on": "Sons du terminal: Oui",
    "ter_sound_off": "Sond du terminal: Non",
    "save_played": "Sauvegarde parties: ",
    "on": "Oui",
    "off": "Non",
    "sound": "Son de jeu: ",
    "alt_control": "Mode clavier: ",
    "show_timer": "Temps de jeu: ",
    "milliseconds": "avec milliseconds: ",
    "fullscreen": "Plein écran: ",
    "live_clock": "Heure: ",
    "ultra_timer": "Temps du jeu Ultra: ",
    "ultra_ms": "Millisecondes Ultra: ",
    "ultra_clock": "Horloge du terminal: ",
    "game_volume": "Volume de jeu",
    "terminal_volume": "Volume de terminal",
    "language": "Langue",
    "u_ter_in_ord": "Ordre de saisie du terminal Ultra",
    "keybindings": "Raccourcis",
    "key_press": "Faire une touche",
    "about_1": "À propos de Mati",
    "about_2": "Mati est un algorithme. Et vraiment un algorithme cool.",
    "about_3": "Il génère le plateau interne et sélectionne des cases au hasard.",
    "about_4": "Les cases sélectionnées sont additionnées et les sommes sont notées.",
    "about_5": "Créé par:",
    "size": "Taille",
    "mode": "Mode",
    "games": "Victoires",
    "best": "Meilleur temps",
    "average": "Temps moyen",
    "achievements": "Succès",
    "unlocked": " déverrouillé",
    "unlocked_overall": "déverrouillés au total",
    "nothing_achieved": "Rien de terminé pour l'instant.",
    "page": "Page",
    "delete_match": "Supprimer la partie?",
    "under_1": "Êtes-vous sûr de vouloir vraiment",
    "under_2": "supprimer définitivement cette partie de votre historique?",
    "delete": "Supprimer",
    "cancel": "Annuler",
    "menu": "Menu",
    "no_history_entries": "Aucune partie enregistrée, du moins pour l'instant.",
    "all": "Toutes",
    "no_matches": "Aucune de vos parties ne correspond aux filtres actifs.",
    "mati": "Mati",
    "intro_text": "Réflexion mathématique et tactique",
    "settings": "Paramètres",
    "history": "Historique",
    "quit": "Quitter",
    "gameplay": "Mécanique de jeu",
    "timer": "Temps de jeu",
    "ultra_mode": "Mode Ultra",
    "display": "Affichage",
    "stats": "Statistiques",
    "about": "À propos",
    "fullscreen_info": "Appuyez sur F11 pour changer de mode ou sur Échap pour quitter le plein écran.",
    "ultra": "ULTRA",
    "ultra_1": "Ultra",
    "normal": "Normal",
    "time": "Temps de jeu: ",
    "hints": "Nb. l'aide: ",
    "action_start": "Action: Début",
    "action": "Action: ",
    "row": " (Ligne: ",
    "column": " / Colonne: ",
    "end": "Fin de la partie",
    "export": "Exporter en MP4",
    "show_end": "Afficher le résultat",
    "start": "Démarrer",
    "action_found": "Aucune action trouvée",
    "continue": "Continuer",
    "new": "Nouveau",
    "undo": "Annuler",
    "hint": "Indice ",
    "won": "Vous avez gagné",
    "paused": "En pause",
    "pressing": "Appuyez sur ",
    "contin": " ou sur <<Continuer>> pour reprendre",
    "unfinished": "Parties en pause trouvées",
    "ask_return": "Voulez-vous reprendre ou commencer une nouvelle partie?",
    "new_game": "Nouvelle partie",
    "resume": "Reprendre",
    "break": "Pause",
    "histo": "Historique",
    "Easy": "Facile",
    "Advanced": "Avancé",
    "Hard": "Difficile",
    "Expert": "Expert",
    "Select": "Sélectionné",
    "Mark": "Marqué",
    "Hint": "Indice",
    "Undone": "Annulé",
    "hannah_com": "Hannah - Message complété",
    "hannah_fou": "Hannah - Message trouvé",
    "Column, Row, Action": "Colonne, Ligne, Action",
    "Row, Column, Action": "Ligne, Colonne, Action",
    "Action, Row, Column": "Action, Ligne, Colonne",
    "Action, Column, Row": "Action, Colonne, Ligne",
    "Back to Menu": "Retour au menu",
    "New Round": "Nouvelle manche",
    "Toggle_Fullscreen": "Plein écran",
    "Use Hint": "Indice",
    "Undo": "Annuler",
    "Pause": "Pause",
    "Right-Click Cell": "Marquer la case",
    "Standard": "Standard",
    "Ultra": "Ultra",
    "High": "Élevé",
    "Highest": "Maximum",
    "milestones_reached": "Jalons atteints",
    "left": "Restant",
    "hover_to_browse": "Survolez pour parcourir",
    "scroll_to_browse": "Faites défiler pour parcourir",
    "games_played": "Parties jouées",
    "total_playtime": "Temps de jeu total",
}

with open("rsc/languages/francais.smati", "w") as f:
    f.write(ps._encode(translations))