import persistence as ps
translations = {
    "settings_title": "Einstellungen",
    "advanced_settings_title": "Erweiterte Einstellungen",
    "back": "Zurück",
    "volume": "Lautstärke",
    "ter_sound_on": "Terminal Sounds: An",
    "ter_sound_off": "Terminal Sounds: Aus",
    "save_played": "Spiele sichern: ",
    "on": "An",
    "off": "Aus",
    "sound": "Spiel-Ton: ",
    "alt_control": "Tastatur Modus: ",
    "show_timer": "Spielzeit anzeigen: ",
    "milliseconds": "mit Millisekunden: ",
    "fullscreen": "Vollbild: ",
    "live_clock": "Uhrzeit: ",
    "ultra_timer": "Ultra Spielzeit:",
    "ultra_ms": "Ultra Millisekunden: ",
    "ultra_clock": "Terminal Uhr: ",
    "game_volume": "Spiel Lautstärke",
    "terminal_volume": "Terminal Lautstärke",
    "language": "Sprache",
    "u_ter_in_ord": "Ultra Terminal Eingabereihenfolge",
    "keybindings": "Verknüpfungen",
    "key_press": "Drücke eine Taste",
    "about_1": "Über Mati",
    "about_2": "Mati ist ein Algorithmus. Ein wirklich cooler.",
    "about_3": "Er generiert das innere Spielfeld and wählt zufällig Felder aus.",
    "about_4": "Die ausgewählten Felder werden addiert und die Summen werden notiert.",
    "about_5": "Erstellt von:",
    "size": "Größe",
    "mode": "Modus",
    "games": "Siegsanzahl",
    "best": "Schnellste Runde",
    "average": "Durchschnittliche Zeit",
    "achievements": "Erfolge",
    "unlocked": " freigeschaltet",
    "unlocked_overall": " insgesamt freigeschaltet",
    "nothing_achieved": "Noch nichts abgeschlossen.",
    "page": "Seite",
    "delete_match": "Partie löschen?",
    "under_1": "Bist du dir sicher, dass du wirklich diese Partie",
    "under_2": "dauerhaft aus deiner Historie löschen möchtest?",
    "delete": "Löschen",
    "cancel": "Abbrechen",
    "menu": "Menü",
    "no_history_entries": "Keine Spiele gespeichert, zumindest bis jetzt.",
    "all": "Alle",
    "no_matches": "Keine deiner Partien entspricht deinen aktiven Filtern.",
    "mati": "Mati",
    "intro_text": "Mathematisches und taktisches denken",
    "settings": "Einstellungen",
    "history": "Historie",
    "quit": "Beenden",
    "gameplay": "Spielmechanik",
    "timer": "Spielzeit",
    "ultra_mode": "Ultra Modus",
    "display": "Anzeige",
    "stats": "Statistiken",
    "about": "Über",
    "fullscreen_info": "Drücke F11 zum Wechseln oder ESC zum Beenden des Vollbild-Modus.",
    "ultra": "ULTRA",
    "ultra_l": "Ultra",
    "normal": "Normal",
    #"time": "Zeit: ",
    "hints": "Hilfe verw.: ",
    "action_start": "Aktion: Start",
    "action": "Aktion: ",
    "row": " (Reihe: ",
    "column": " / Spalte: ",
    "end": "Ende des Spiels",
    "export": "Als MP4 exportieren",
    "show_end": "Endstand zeigen",
    "start": "Start",
    "action_found": "Keine Aktionen gefunden",
    "continue": "Weiter",
    "new": "Neu",
    "undo": "Rückgängig",
    "hint": "Hinweis ",
    "time": "Spielzeit: ",
    "won": "Du hast gewonnen",
    "paused": "Pausiert",
    "pressing": "Drücke ",
    "contin": " oder <<Weiter>> zum weiterspielen",
    "unfinished": "Pausierte Spiele gefunden",
    "ask_return": "Möchtest du weiterspielen oder ein neues Spiel starten?",
    "new_game": "Neues Spiel",
    "resume": "Weiter spielen",
    "break": "Pause",
    "histo": "Historie",
    "Easy": "Einfach",
    "Advanced": "Fortgeschritten",
    "Hard": "Kompliziert",
    "Expert": "Experte",
    "Select": "Ausgewählt",
    "Mark": "Makiert",
    "Hint": "Hinweis",
    "Undone": "Zurückgenommen",
    "hannah_com": "Hannah - Nachricht vervollständigt",
    "hannah_fou": "Hannah - Nachricht gefunden",
    "Column, Row, Action": "Spalte, Reihe, Aktion",
    "Row, Column, Action": "Reihe, Spalte, Aktion",
    "Action, Column, Row": "Aktion, Spalte, Reihe",
    "Action, Row, Column": "Aktion, Reihe, Spalte",
    "Back to Menu": "Zurück ins Menü",
    "New Round": "Neue Runde",
    "Toggle Fullscreen": "Vollbildmodus",
    "Use Hint": "Hinweis",
    "Undo": "Rückgängig",
    "Pause": "Pause",
    "Right-Click Cell": "Feld makieren",
    "Standard": "Standard",
    "High": "Hoch",
    "Ultra": "Ultra",
    "Highest": "Höchstes",
    "milestones_reached": "Vervollständigt!",
    "left": "übrig", # sence of missing
    "hover_to_browse": "Hover mich!",
    "scroll_to_browse": "Scroll mich!",
    "games_played": "Spiele gespielt",
    "total_playtime": "Spielzeit",
}
with open("rsc/languages/deutsch.smati", "w") as f:
    f.write(ps._encode(translations))